name = "question"
version = "1.0.1"

description = "Simple wrapper function to grab user input. For CLI tools"
licences = ["Apache-2.0"]
repository = { type = "github", user = "antonioxdias", repo = "question" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
